name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
    # cron: '00 15 * * *'로 하면 한국 시간 기준으로 오전 12:00에 업데이트 된다
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{waka_0d9b6c6f-2285-47e2-bdc9-0e98b540a228}}
          GH_TOKEN: ${{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}}
          # 플래그 자리
